workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - clean
    - build
    - test
    - package
    - deploy

cache:
  paths:
    - .m2/repository
    - target

clean_job:
  stage: clean
  tags:
    - docker

  script:
    - echo "Maven clean started"
    - "cd logging-service && mvn clean"

build_job:
  stage: build
  tags:
    - docker 

  script: 
    - echo "Maven compile started"
    - "cd logging-service && mvn compile"


test_job:
  stage: test
  tags:
    - docker 

  script: 
    - echo "Maven test started"
    - "cd logging-service && mvn test"

package_job:
  stage: package
  tags:
    - docker 

  script: 
    - echo "Maven packaging started"
    - "cd logging-service && mvn package"

deploy_job:
  stage: deploy
  tags:
    - docker

  script:
    - echo "Deployment initiated"

  rules:
    - if: '$TRIGGER_SOURCE == "merge_request_event"'
