workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  ATLAS_TEST_URI: "$ATLAS_TEST_URI"
  HIVE_CLIENT_NAME: "$HIVE_CLIENT_NAME"
  HIVE_URL: "$HIVE_URL"
  HIVE_USER: "$HIVE_USER"
  HIVE_PW: "$HIVE_PW"

image: maven:latest

stages:
    - clean
    - build
    - test
    - package

cache:
  paths:
    - .m2/repository
    - target

clean_job:
  stage: clean
  tags:
    - docker

  script:
    - echo "Maven clean started"
    - "cd timeslot-service && mvn clean"

build_job:
  stage: build
  tags:
    - docker 

  script: 
    - echo "Maven compile started"
    - "cd timeslot-service && mvn compile"


test_job:
  stage: test
  tags:
    - docker 

  script: 
    - echo "Maven test started"
    - "cd timeslot-service && mvn test"

package_job:
  stage: package
  tags:
    - docker 

  script: 
    - echo "Maven packaging started"
    - "cd timeslot-service && mvn package"
